Modules/M_XI/Exercises/1 - Layers/1.1 - Presentation/CIPSA.M_XI.WebUI/Controllers/AgendaController.cs
using AutoMapper;
using CIPSA.M_XI.Contract.Application.DTO.Exercise.Agenda;
using CIPSA.M_XI.Contract.Application.ServiceContract.Exercise.Agenda;
using CIPSA.M_XI.WebUI.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CIPSA.M_XI.WebUI.Controllers
{
    public class AgendaController : Controller
    {
        public IEmployeeApplicationService _employeeApplicationService { get; }

        public AgendaController(IEmployeeApplicationService employeeApplicationService)
        {
            _employeeApplicationService = employeeApplicationService;
        }

        public ActionResult Persons()
        {
            return View(Mapper.Map<IEnumerable<EmployeeDto>, IEnumerable<EmployeeModel>>(_employeeApplicationService.GetAll()));
        }

        public ActionResult FindPerson()
        {
            return View();
        }

        public ActionResult EmployeeManagement() {
            return View(Mapper.Map<IEnumerable<EmployeeDto>, IEnumerable<EmployeeManagementModel>>(_employeeApplicationService.GetAll()));
        }
    }
}

Modules/M_XI/Exercises/1 - Layers/1.1 - Presentation/CIPSA.M_XI.WebUI/Controllers/ShopController.cs
using AutoMapper;
using CIPSA.M_XI.Contract.Application.DTO.Exercise.Shop;
using CIPSA.M_XI.Contract.Application.ServiceContract.Exercise.Shop;
using CIPSA.M_XI.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CIPSA.M_XI.WebUI.Controllers
{
    public class ShopController : Controller
    {
        #region .: Properties :.
        public IMovieApplicationService _movieApplicationService { get; }
        public IGameApplicationService _gameApplicationService { get; }
        public IClientApplicationService _clientApplicationService { get; }
        public IRentalApplicationService _rentalApplicationService { get; }
        #endregion

        #region .: Constructor :.
        public ShopController(IMovieApplicationService movieApplicationService,
            IGameApplicationService gameApplicationService,
            IClientApplicationService clientApplicationServic,
            IRentalApplicationService rentalApplicationService)
        {
            _movieApplicationService = movieApplicationService;
            _gameApplicationService = gameApplicationService;
            _clientApplicationService = clientApplicationServic;
            _rentalApplicationService = rentalApplicationService;
        }
        #endregion

        #region .: Public Methods :.
        public ActionResult MovieManagement()
        {
            ViewBag.DeviceOptions = GetDeviceOptions();

            return View(Mapper.Map<IEnumerable<MovieDto>, IEnumerable<MovieManagementModel>>(_movieApplicationService.GetAll()));
        }

        public ActionResult GameManagement()
        {
            ViewBag.PlatformOptions = GetPlatformOptions();

            return View(Mapper.Map<IEnumerable<GameDto>, IEnumerable<GameManagementModel>>(_gameApplicationService.GetAll()));
        }

        public ActionResult ClientManagement()
        {
            return View(Mapper.Map<IEnumerable<ClientDto>, IEnumerable<ClientManagementModel>>(_clientApplicationService.GetAll()));
        }

        public ActionResult PendingRentedArticles()
        {
            ViewBag.NIFOptions = GetNIFOptions();
            return View();
        }

        public ActionResult RentedArticles()
        {
            return View(Mapper.Map<IEnumerable<MovieDto>, IEnumerable<RentedArticleModel>>(_movieApplicationService.GetAll()));
        }

        public ActionResult RegisterRental()
        {
            var registerRentalModel = new RegisterRentalModel
            {
                Articles = Mapper.Map<IEnumerable<GameDto>, List<RentedArticleModel>>(_gameApplicationService.GetNonRentedGames()),
                Clients = Mapper.Map<IEnumerable<ClientDto>, List<ClientManagementModel>>(_clientApplicationService.GetAll())
            };
            return View(registerRentalModel);
        }

        public ActionResult ReturnArticle()
        {
            return View();
        }

        public ActionResult LateRental()
        {
            return View( Mapper.Map<IEnumerable<LateRentalDto>, List<RentalModel>>(_rentalApplicationService.GetLateRentals(-4)) );
        }
        #endregion

        #region .: Private Methods :.
        private IEnumerable<SelectListItem> GetDeviceOptions()
        {
            return new List<SelectListItem>
            {
                new SelectListItem() { Text = "", Value = "" },
                new SelectListItem() { Text = DeviceEnum.BluRay.ToString(), Value = DeviceEnum.BluRay.ToString() },
                new SelectListItem() { Text = DeviceEnum.DVD.ToString(), Value = DeviceEnum.DVD.ToString() }
            };
        }

        private IEnumerable<SelectListItem> GetPlatformOptions()
        {
            return new List<SelectListItem>
            {
                new SelectListItem() { Text = "", Value = "" },
                new SelectListItem() { Text = PlatformEnum.PS3.ToString(), Value = PlatformEnum.PS3.ToString() },
                new SelectListItem() { Text = PlatformEnum.XBOX360.ToString(), Value = PlatformEnum.XBOX360.ToString() },
                new SelectListItem() { Text = PlatformEnum.WII.ToString(), Value = PlatformEnum.WII.ToString() }
            };
        }

        private IEnumerable<SelectListItem> GetNIFOptions()
        {
            var clientsNif = new List<SelectListItem> {
                new SelectListItem() { Text = "", Value = "" }
            };
            _clientApplicationService.GetClientsNIF().ToList().ForEach(clientNif => clientsNif.Add(new SelectListItem() { Text = clientNif, Value = clientNif }));
            return clientsNif;
        }
        #endregion
    }
}

Modules/M_XI/Exercises/1 - Layers/1.1 - Presentation/CIPSA.M_XI.WebUI/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CIPSA Master App - M_XI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="dropdown nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Agenda
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Listas Personas", "Persons", "Agenda", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Buscar Persona", "FindPerson", "Agenda", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Gestión de Personas", "EmployeeManagement", "Agenda", null, new { @class = "dropdown-item" })
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tienda
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Gestión de películas", "MovieManagement", "Shop", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Gestión de juegos", "GameManagement", "Shop", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Gestión de clientes", "ClientManagement", "Shop", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Artículos alquilados pendientes", "PendingRentedArticles", "Shop", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Listar Artículos", "RentedArticles", "Shop", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Registrar Alquiler", "RegisterRental", "Shop", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Devolver Producto", "ReturnArticle", "Shop", null, new { @class = "dropdown-item" })
                            </li>
                            <li>
                                @Html.ActionLink("Listado de alquileres fuera de plazo", "LateRental", "Shop", null, new { @class = "dropdown-item" })
                            </li>
                            
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CIPSA Master App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/jqueryui")
    @RenderSection("scripts", required: false)
</body>
</html>