Modules/M_VI/CIPSA.M_VI.WebApp/Controllers/ExerciseElevenController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

namespace CIPSA.M_VI.WebApp.Controllers
{
    public class ExerciseElevenController : ApiController
    {
        private Dictionary<string, string> wordsEnabledToTranslate = new Dictionary<string, string>() {
                { "acción", "action" },
                { "edad", "age" },
                { "aire", "air" },
                { "animal", "animal" },
                { "respuesta", "answer" },
                { "manzana", "apple" },
                { "arte", "art" },
                { "bebé", "baby" },
                { "espalda", "back" },
                { "banco", "bank" },
                { "cama", "bed" },
                { "factura", "bill" },
                { "pájaro", "bird" },
                { "sangre", "blood" },
                { "barco", "boat" },
                { "cuerpo", "body" },
                { "hueso", "bone" },
                { "fondo", "bottom" },
                { "caja", "box" },
                { "niño", "boy" },
                { "hermano", "brother" },
                { "negocio", "business" },
                { "llamada", "call" }
            };

        // GET api/<controller>
        public IEnumerable<string> Get()
        {
            return wordsEnabledToTranslate.Keys.Select(key => key);
        }

        // GET api/<controller>/5
        public string Get(string id)
        {
            wordsEnabledToTranslate.TryGetValue(id.ToLower(), out string wordTranslated);

            return wordTranslated ?? string.Empty;
        }
    }
}

Modules/M_VI/CIPSA.M_VI.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CIPSA.M_VI.WebApp.Controllers
{
    public class HomeController : Controller
    {      
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ExerciseEleven()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

Modules/M_VI/CIPSA.M_VI.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CIPSA Master App - M_VI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ejercicio 11", "ExerciseEleven", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CIPSA Master App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>